### ISSUE TITLE
Читы не работают!

### ISSUE THREAD

**Issue by Hu4uTa** [u1qqlv/SURVIV.IO-PRO-HACK#11]
Сделал всё как ты написал в инструкции, а оно не работает(

**Comment by u1qqlv** [comment]
oni robotaiut 

Fill "Tab URL:" input with "\*surviv.io\*" website (IMPORTANT! add \* before and after surviv.io)
"From" input with surviv.io current file: "\*surviv.io/js/app.\*.js" (IMPORTANT! add \* before URL (maybe this is the last time we need to change URL LOL))
"To" input with our hack JS File URL: "https://rawcdn.githack.com/u1qqlv/SURVIV.IO-PRO-HACK/07fa9e5586d5bb99497100380a86fa0b798fc770/app.d0bfe7b9.js"

**Comment by u1qqlv** [comment]
![687474703a2f2f6936382e74696e797069632e636f6d2f356c346670332e706e67](https://user-images.githubusercontent.com/50009701/57865134-b64a4100-7805-11e9-8260-f4a64f50318b.png)
