### ISSUE TITLE
The game is freezing...

### ISSUE THREAD

**Issue by system123786** [u1qqlv/SURVIV.IO-PRO-HACK#13]
About 2 minutes into a game the game freezes for some reason so if you have any spare time could you please fix them

**Comment by u1qqlv** [comment]
I played one game and no problems, but I will play more and test

**Comment by u1qqlv** [comment]
Is the game still freezing? Or it is over?

**Comment by reflexin** [comment]
> Is the game still freezing? Or it is over?

I play with this daily and haven't experienced a single freeze.
