### ISSUE TITLE
freezes!!!!!!!

### ISSUE THREAD

**Issue by 28052005** [u1qqlv/SURVIV.IO-PRO-HACK#17]

**Comment by u1qqlv** [comment]
try to update the value again and tell me if it is the same...

**Comment by khoint0210** [comment]
😢 It still freezes

**Comment by 28052005** [comment]
sometimes freezes

**Comment by u1qqlv** [comment]
I don't know how to fix freezes, it hard to find out, I leave

**Comment by humphreygaming** [comment]
it is possible to fix freezes, its just a matter of websocket interference and reading signals/code sent to surviv (certain lines/variables in the code can cause this)

**Comment by u1qqlv** [comment]
not freezing now
