### ISSUE TITLE
auto aim doesnt work 

### ISSUE THREAD

**Issue by ScripterLima** [u1qqlv/SURVIV.IO-PRO-HACK#29]
ma dud idk i cant see it work

**Comment by u1qqlv** [comment]
put this URL

 https://rawcdn.githack.com/u1qqlv/SURVIV.IO-PRO-HACK/b3d5fd537e77f55d0eba3235a75cd3277d1b4e8b/app.7dbf9b57.js

**Comment by u1qqlv** [comment]
and it works just tested
