### ISSUE TITLE
Bug at 15x sight

### ISSUE THREAD

**Issue by anonymort** [u1qqlv/SURVIV.IO-PRO-HACK#33]
Minor bug, but when you get a 15x sight it will draw a line to all other sights within range even if you already have them. See screenshot, when I picked up the 15x sight at the end loads of lines appeared to nearby 2x, 4x, 8x sights.

<img width="1910" alt="bug" src="https://user-images.githubusercontent.com/57272605/69900837-4f8b1000-1370-11ea-852d-401d55540519.PNG">

**Comment by u1qqlv** [comment]
yeah I think I fixed it, on my local js file, I will update later when new game update will be available + bumpfire, maybe other stuff...
Why you kicked me form icehacks discord? not cool

**Comment by anonymort** [comment]
I didn't, I was also kicked.

**Comment by u1qqlv** [comment]
you did this

**Comment by u1qqlv** [comment]
fixed on new update
