### ISSUE TITLE
What to do when new updates

### ISSUE THREAD

**Issue by DripxPlugz** [u1qqlv/SURVIV.IO-PRO-HACK#35]
what do we have to do when there is a new update

**Comment by u1qqlv** [comment]
wait for me to update the hack :) 
I tried but an error occurred I need to find out...

**Comment by hallen2023** [comment]
when can we expect an update?

**Comment by ScripterLima** [comment]
guys wait it takes time to find the anti cheat bypass

**Comment by u1qqlv** [comment]
updated!
https://rawcdn.githack.com/u1qqlv/SURVIV.IO-PRO-HACK/87c47ff4cbdf5f3b7b92e23c48b26306692ad641/app.93a611bc.js
