### ISSUE TITLE
Aimbot update

### ISSUE THREAD

**Issue by jslagel2023** [u1qqlv/SURVIV.IO-PRO-HACK#37]
how long does it take to update the aimbot, also when will it be up again

**Comment by Dirk04** [comment]
I would also like to know this has been very helpful these tricks

**Comment by carmencassidy0** [comment]
this has helped me a lot i would be happy to know when they are updated

**Comment by u1qqlv** [comment]
I want to improve a little bit before I update

**Comment by u1qqlv** [comment]
updated! not much
