### ISSUE TITLE
Patched at v 0.8.8.1

### ISSUE THREAD

**Issue by adams-here-1** [u1qqlv/SURVIV.IO-PRO-HACK#38]
Did it get patched?
I just get "new version available" and "old client version"

**Comment by u1qqlv** [comment]
this game is updated so often I got lazy updating it :D

**Comment by u1qqlv** [comment]
the update is nothing new, 50 v 50 is an old mode :D maybe something new will come and I will update...

**Comment by jslagel2023** [comment]
so there isn't going to be an aimbot for a while?

**Comment by u1qqlv** [comment]
https://rawcdn.githack.com/u1qqlv/SURVIV.IO-PRO-HACK/c8d885bf0c7072d6bdb262f69ccdbe1ca12f93d7/default/app.bd216fc3.js
