### ISSUE TITLE
Doesn't seem to be working.

### ISSUE THREAD

**Issue by brendnnn** [u1qqlv/SURVIV.IO-PRO-HACK#39]
I put in all of the correct info and used ctrl f5, but still doesn't work. 
![Screenshot 2019-12-21 at 3 34 01 PM](https://user-images.githubusercontent.com/59124707/71313503-a7fd7c80-2407-11ea-8cfb-684e80c6d90d.png)

**Comment by u1qqlv** [comment]
add *
before surviv.io/js/app.**.js
