### ISSUE TITLE
Cant shoot

### ISSUE THREAD

**Issue by pilgrimoflight** [u1qqlv/SURVIV.IO-PRO-HACK#4]
Installed cheat, sems everything okay, but when i press LMB to shoot it switches to hands and punches only.
Fire is set to LMB. Dont know what is wrong though

**Comment by u1qqlv** [comment]
can not replicate

**Comment by Exerciz** [comment]
@u1qqlv If you set changing weapon one and two with ''Right Mouse Click''  you can't shoot ingame, it just switches fast weapons. Solve this problem please. Let us change weapon 1 and 2 with just a right mouse click

**Comment by u1qqlv** [comment]
should be fixed for now... check new update
