### ISSUE TITLE
well im not trying to bug you or anything im trying to use your hacks and it doesnt work because of the winter update. but i also dont want to use the icehacks because it delays my game alot and i lag..

### ISSUE THREAD

**Issue by IhavenADw** [u1qqlv/SURVIV.IO-PRO-HACK#43]
well im not trying to bug you or anything im trying to use your hacks and it doesnt work because of the winter update. but i also dont want to use the icehacks because it delays my game alot and i lag..

**Comment by u1qqlv** [comment]
I am lazy updating, I have the game file already, icehacks lags?? report it there...

**Comment by u1qqlv** [comment]
dane
