### ISSUE TITLE
Shoot/Switch

### ISSUE THREAD

**Issue by Exerciz** [u1qqlv/SURVIV.IO-PRO-HACK#5]
Hey u1qqlv,

The Hack is really great & everything works nice, including the aimbot.
But like I said one thing i hate... the switch problem...

If I set the switch keybind between weapon one and two with the ''right mouse click'' i can't anymore shoot. If i try to shoot it just switches weapons even if the keybind is on left mouse click for fire. Please solve the problem.

**Comment by pilgrimoflight** [comment]
Also, if you want to play with friend Duo or Squad - cheat will work only for one ,who creates match. 
Tested that.

P.S. I dont care about Duo so much, but this issue exists =)

**Comment by Exerciz** [comment]
Yes, right. Thats why i try to create matches by my own when playing squads or duos.

**Comment by u1qqlv** [comment]
can you retest quad or team invite, instructions updated!

**Comment by u1qqlv** [comment]
@Exerciz hi, can you retest if it works plz

**Comment by Exerciz** [comment]
Nope the switching doesn't works please fix the problem @u1qqlv

**Comment by u1qqlv** [comment]
Now it is fixed.

**Comment by u1qqlv** [comment]
update to new game file
